### PR TITLE
Hybridize

### PR DESCRIPTION
**Pull request by dlockhart**
@awikkerink First attempt... tests are failing though and I'm not quite sure why. I probably missed something with the DOM APIs changing?

### CODE REVIEW

**Comment by awikkerink** [comment]
Doesn't look like it works correctly in the demos. The Polymer 2 demos aren't working at all and the Polymer 1 demos styles are off.

**Comment by dlockhart** [comment]
Interesting -- Polymer 2.0 demos are working perfectly for me. The Polymer 1 demos can't work, since `<button is="d2l-button">` -> `<d2l-button>`. I guess I should just force the new version of button then eh?

**Comment by awikkerink** [comment]
button-group doesn't depend on `d2l-button`. It is just used for the demos and tests

**Comment by awikkerink** [comment]
I'm seeing:

`items.filter is not a function`
`A <template> can only be templatized once`

**Comment by dlockhart** [comment]
I think it does need `<d2l-button>`:
https://github.com/BrightspaceUI/button-group/blob/master/d2l-buttons-menu.html#L85

**Comment by awikkerink** [comment]
Ah, I missed that. The d2l-button.html import is missing.

**Pull request closed without merging**
