### PR TITLE
Hybridize

### PR DESCRIPTION
**Pull request by dbatiste**

### CODE REVIEW

**Comment by awikkerink** [comment]
The More actions button isn't getting replaced with `...`

127 0 0 1_8001_components_d2l-button-group_ 1

**Comment by dbatiste** [comment]
Thanks, I'll take a look.

**Comment by awikkerink** [comment]
:+1: Much better! The `...` still wraps to the next line. Which isn't terrible I suppose and the screen will never be that small.

**Comment by dbatiste** [comment]
Yeah.  Thanks for looking at this Anthony.

By the way, would you like to stay on as one of the code owners?  I don't mind taking it over... it's up to you.  :)

**Pull request merged**
